<head>  
 
 
    <?php echo $this->headScript()->appendFile('/js/jquery-1.3.2.min.js') ?>
    <?php echo $this->headScript()->appendFile('/js/script.js') ?>
    
    <?php echo $this->headScript()->appendFile('/js/roundabout.js') ?>
    <?php echo $this->headScript()->appendFile('/js/easing.js') ?>
    <?php echo $this->headScript()->appendFile('/js/roundabout_shapes.js') ?>
    
    


</head>  

<div class="line">&nbsp;</div> 

<div id="main">
    <!-- content -->
    <section id="content">               
      <!-- .content-box -->
      <div class="inside1">
          <div class="content-box">
            <div class="container_12 wrapper">
                <div class="grid_8 alpha">
                	<div class="indent">
                        <h2>Testimonials</h2><br />
                       	<div class="wrapper p1"><a href="images/howtruckerswork.jpg"  class="lightbox-image fleft" rel="prettyphoto" title="How allstateloads work for truckers"><img alt="How allstateloads work for truckers" src="images/howtruckerswork0.jpg" class="img-indent3" /></a><a href="images/howtruckersworks.jpg"  class="lightbox-image fleft"  rel="prettyphoto" title="How allstateloads work for truckers"><img alt="How allstateloads work for truckers" src="images/howtruckerswork00.jpg" class="img-indent3" /></a></div>
                        <p><b>Truckers find loads for your truck. Use this system to post your trucks and find the loads that you can carry</b></p>
                         
                         
                        <p>Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridicu-<br>lus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lor<br>
                        em. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit. Aene<br>an auctor wisi et urna. Aliquam erat volutpat duis ac turpis. Intege.</p>                        
                    </div>
                    <div class="indent2">
                    	 <div class="container_8 wrapper">
                         	<div class="grid_4 alpha">
                            	<div class="inside-right1">
                                    <h2>What we offer</h2>
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipitvariusim cum sociis natoque penatibus et.</p>
                                    <p>Aenean nonummy hendrerit mauris. Phasel-<br>lus porta. Fusce suscipitvariusim cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus.</p>
                                    <ul class="list1">                                        
                        <li>Post Trucks Unlimited</li>

						<li>Search Freights Unlimited</li>

						<li> Broker Credit Scores</li>
						<li>Search Mulitple Results</li>

						<li>Get Notification Instantly </li>
                                    </ul>
                                </div>
                            </div>
                         	<div class="grid_4 omega">
                            	<h2>Our advantages</h2>
                                <ol>
                                    <li><a href="#">Sed in lacus ut enim adipiscing aliqu  fusce euismod consequat ante.</a><br>
                                    	<p>Dolor sit amet, consectetuer adipiscing elit. Pellentesque sed dolor. Aliquam confermentum<br>
                                        nisl. Mauris accumsan nulla vel diam. Sed in <br>
                                        lacus ut enim adipiscing aliquet. Nulla venena-<br>
                                        tis. In pede mi, aliquet sit a met, euismod in, <br>
                                        auctor ut, ligula liquam.</p>
                                    </li>
                                    <li><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed dolor. </a><br>
                                        <p>Aliquam confermentum nisl. Mauris accumsan<br>
                                        nulla vel diam. Sed in lacus ut enim adipiscing <br>
                                        aliquet. Nulla venenatis. In pede mi, aliquet sit<br>
                                        amet, euismod in, auctor ut, ligula. Aliquam<br>
                                        dapibus tincidunt metus. Praesent justo dolor,<br>
                                        lobortis quis, lobortis dignissim, pulvinar ac,<br>
                                        lorem. Vestibulum sed ante. Donec sagittis im<br>
                                        euismod purus lacus ut enim.</p>
                                    </li>
                                </ol>
                            </div>
                         </div>
                    </div>
                </div>
                
                <div class="grid_4 omega">
                	<h2>Latest news</h2>
                    <ul class="news">
                        <li>
                          <p class="date">08<span>April</span></p>
                          <a href="#" class="title">Parturient montes, nascetur ridiculus mu nulla dui fusce feugiat malesuada odio morbi nunc gravida.</a>
                        </li>
                      </ul>
                      <p>Fusce feugiat malesuada odio. Morbi nunc odio, gravi<br>da at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci... <a href="more.html" class="link">&gt;</a></p>
                   	 <ul class="news">
                        <li>
                          <p class="date">22<span>April</span></p>
                          <a href="#" class="title">Nulla dui fusce feugiat malesuada odio morbi nunc gravida  at, cursus nec, luctus a, lorem naecenas.</a>
                        </li>
                      </ul>
                      <p>Duis ultricies pharetra magna. Done accumsan male-<br>suada orci adipiscing elit.Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapi-<br>bus eget, elementum vel... <a href="more.html" class="link">&gt;</a></p>
                      
                    <a href="more.html" class="button">Viev All News</a>                    
                    <div class="indent2">
                        <h2>Testimonials</h2>
                        <b>Patrick Pool</b>, student, May 18, 2010
                        <p>"Cum sociis natoque penatibus et magnis dis parturi-<br>ent montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem..." <a href="more.html" class="link">&gt;</a></p>
                        <b>Sandra Bullock</b>, driver, May 21, 2010
                        <p>"Morbi nunc odio, gravida at, cursu nec, luctus a lorem maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum..." <a href="more.html" class="link">&gt;</a></p>
                        <b>Alan Smith</b>, driver, June 27, 2010
                        <p>"Nascetur ridiculus mus. Nulla dui. Fusce feugi at mal<br>esuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna..." <a href="more.html" class="link">&gt;</a></p>
                    	<a href="more.html" class="button">More Testimonials</a>           
                    </div>         
                </div>
                
                
                <div class="grid_8 alpha">
                	<div class="indent">
                        <h2>How allStateLoads Work for Loaders</h2>
                       	<div class="wrapper p1"><a href="images/howloaderswork.jpg"  class="lightbox-image fleft" rel="prettyphoto" title="How allstateloads work for loaders"><img alt="How allstateloads work for loaders" src="images/howloaderswork0.jpg" class="img-indent3" /></a><a href="images/howloadersworks.jpg"  class="lightbox-image fleft"  rel="prettyphoto" title="How allstateloads work for loaders"><img alt="How allstateloads work for loaders" src="images/howloaderswork00.jpg" class="img-indent3" /></a></div>
                        <p><b>Truckers find loads for your truck. Use this system to post your trucks and find the loads that you can carry</b></p>
                         
                        <p>Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridicu-<br>lus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lor<br>
                        em. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit. Aene<br>an auctor wisi et urna. Aliquam erat volutpat duis ac turpis. Intege.</p>                        
                    </div>
                    <div class="indent2">
                    	 <div class="container_8 wrapper">
                         	<div class="grid_4 alpha">
                            	<div class="inside-right1">
                                    <h2>What we offer</h2>
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipitvariusim cum sociis natoque penatibus et.</p>
                                    <p>Aenean nonummy hendrerit mauris. Phasel-<br>lus porta. Fusce suscipitvariusim cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus.</p>
                                    <ul class="list1">                                        
                        
                        <li>Post Unlimited Freight </li>

						<li>Search Unlimited Trucks </li>

						<li>Truck Notification Instantly </li>

						<li>Lane Posting Unlimited </li>
                                    </ul>
                                </div>
                            </div>
                         	<div class="grid_4 omega">
                            	<h2>Our advantages</h2>
                                <ol>
                                    <li><a href="#">Sed in lacus ut enim adipiscing aliqu  fusce euismod consequat ante.</a><br>
                                    	<p>Dolor sit amet, consectetuer adipiscing elit. Pellentesque sed dolor. Aliquam confermentum<br>
                                        nisl. Mauris accumsan nulla vel diam. Sed in <br>
                                        lacus ut enim adipiscing aliquet. Nulla venena-<br>
                                        tis. In pede mi, aliquet sit a met, euismod in, <br>
                                        auctor ut, ligula liquam.</p>
                                    </li>
                                    <li><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed dolor. </a><br>
                                        <p>Aliquam confermentum nisl. Mauris accumsan<br>
                                        nulla vel diam. Sed in lacus ut enim adipiscing <br>
                                        aliquet. Nulla venenatis. In pede mi, aliquet sit<br>
                                        amet, euismod in, auctor ut, ligula. Aliquam<br>
                                        dapibus tincidunt metus. Praesent justo dolor,<br>
                                        lobortis quis, lobortis dignissim, pulvinar ac,<br>
                                        lorem. Vestibulum sed ante. Donec sagittis im<br>
                                        euismod purus lacus ut enim.</p>
                                    </li>
                                </ol>
                            </div>
                         </div>
                    </div>
                </div>
                
                
            </div>
          </div>
      </div>
      <!-- /.content-box -->
    </section>
</div>




			
			