
<!-- pitch -->
			<div id="pitch">
				<div id="slideshow">
					
					<!-- 1st frame -->
					
					
					<!-- 3rd frame -->
					<div>
						<img src="../images/pitch/pitch1.jpg" alt="" />
						<div class="overlay transparent">
							<h2>Loads of Business</h2>
							<p>Using All State Loads brings in loads of business for Truckers and Freight forwarders.</p>
						</div>
						
					</div>
					<!-- 3rd frame -->
					
				</div>
			</div>
			<!-- /pitch -->
			
			<!-- main -->
			<div id="main">
<h2 class="inner">Login Here</h2>
<p>				
<?php echo $this->form; ?>
<?php echo $this->error; ?>
</p>

</div>

