<div class="line">&nbsp;</div> 
<div id="main">
    <!-- content -->
    <section id="content">               
      <!-- .content-box -->
      <div class="inside1">
          <div class="content-box">
            <div class="container_12 wrapper">
                <div class="grid_7 alpha">
                        <h2>Sign up Here</h2><br />
                         <div id="contact_form">
                                	
                                   <?php echo $this->form; ?>


                              </div>
                </div>
                <div class="grid_5 omega">
                    <h2>More</h2>
                    <a href="#"></a><br>
                    <dl class="address">
                        <dt>The Company Name Inc.<br />
                        8901 Marmora Road, Glasgow, D04 89GR.</dt>  
                      <dd><span>Freephone:</span>+1 800 559 6580</dd>
                      <dd><span>Telephone:</span>+1 959 603 6035</dd>
                      <dd><span>FAX:</span>+1 504 889 9898</dd>
                      <dd><span>E-mail:</span><a href="#"><strong>mail@demolink.org</strong></a></dd>
                    </dl>
                </div>
            </div>
          </div>
      </div>
      <!-- /.content-box -->
    </section>
</div>


