
<<div class="line">&nbsp;</div> 
<div id="main">
    <!-- content -->
    <section id="content">               
      <!-- .content-box -->
      <div class="inside1">
          <div class="content-box">
            <div class="container_12 wrapper">
                <div class="grid_4 alpha">
                	<div class="indent">
                        <h2>Services list</h2>
                        <ul class="list2">
                            <li><a href="#">Sed in lacus ut adipiscing</a><br>
                            consectetuer adipiscing elit pelle<br>sed dolor aliquam... <a href="more.html" class="link">&gt;</a></li>       
                            <li class="li"><a href="#">Pellentesque sed dolor</a><br>
                            adipiscing elit pellentesq sedino <br>quam conferm entum... <a href="more.html" class="link">&gt;</a></li>       
                            <li class="li1"><a href="#">Adipiscing eli pellentesque</a><br>
                            sed dolor aliquam conferm entu<br>mauris accumsan... <a href="more.html" class="link">&gt;</a></li>       
                            <li class="li2"><a href="#">Confermentum nisl mauris</a><br>
                            conferm entum nisl mauris accu<br>nulla vel diam sed in... <a href="more.html" class="link">&gt;</a></li>       
                            <li class="li3"><a href="#">Mauris accumsan nulla</a><br>
                            lacus ut enim adipiscing aliquet<br>venenatis pede aliquet... <a href="more.html" class="link">&gt;</a></li>       
                            <li class="li4"><a href="#">Lacus ut enim adipiscing ali</a><br>
                            venenatis pede mi aliquet sit a<br>ismod in auctor ligula... <a href="more.html" class="link">&gt;</a></li>                            
                        </ul>
                    </div>
                </div>
                <div class="grid_8 omega">
                	<h2>Featured services</h2>
                    <div class="wrapper">
                    	<figure><a href="images/img-3.jpg" class="lightbox-image1 lightbox-image" rel="prettyphoto" title="Example 1"><img alt="" src="images/5page_img1.jpg" /></a></figure>
                        <p><b>Lacus ut enim adipiscing aliqu  fusce euismod consequat ante. Lorem ipsum dolor sit amet.</b></p>
                        <p>Dolor sit amet, consectetuer adipiscing elit. Pellentesque sed dolor. Aliquam confermentum nisl. Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit a met, euismod in, auctor ut, ligula liquam dapibus tinci-<br>dunt met usto dolor, lobortis... <a href="more.html" class="link">&gt;</a></p>
                        <br class="clear" />
                    </div> 
                    <div class="wrapper">
                    	<figure><a href="images/img-4.jpg" class="lightbox-image1 lightbox-image" rel="prettyphoto" title="Example 1"><img alt="" src="images/5page_img2.jpg" /></a></figure>
                        <p><b>Fusce euismod consequat ante. Lorem ipsum dolor sit amet consectetuer adipiscing elit.</b></p>
                        <p>Pellentesque sed dolor. Aliquam confermentum nisl. Mauri accum-<br>san nulla vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit a met, euismod in, auctor ut, ligula liquam dapibus tincidunt metus. Praesent justo dolor, lobortis quis lobortis dignissim pulvinar ac... <a href="more.html" class="link">&gt;</a></p>
                        <br class="clear" />
                    </div> 
                    <div class="wrapper">
                    	<figure><a href="images/img-5.jpg" class="lightbox-image1 lightbox-image" rel="prettyphoto" title="Example 1"><img alt="" src="images/5page_img3.jpg" /></a></figure>
                        <p><b>Ellentesque sed dolor aiquam congue fermentum nisl mauris in<br>accumsan nulla vel diam sed in.</b></p>
                        <p>Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit a met, euismod in, auctor ut, ligula liquam dapibus tincidunt metus. Praesent justo dolor, lobortis quis, lobortis dignissim, pulvinar ac, lorem. Vestibu-<br>lum sed ante sagittis euismod purus... <a href="more.html" class="link">&gt;</a></p>
                        <br class="clear" />
                    </div> 
                </div>
            </div>
          </div>
          <div class="indent2">
          		<h2>Best proposals</h2>
                <div class="wrapper">
                    <figure><a href="images/img-6.jpg" class="lightbox-image1 lightbox-image" rel="prettyphoto" title="Example 1"><img alt="" src="images/5page_img4.jpg" /></a></figure>
                    <p><b>Fusce euismod consequat ante. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque sed dolor. Aliquam congue fermentum nisl. Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing.</b></p>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent vestibulum molestie lacus. Aenean nonummy hendreritma
                    uris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur rid
                    iculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci.Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris fermentum dictum magna. </p>
                    <div class="indent3">
                        <ul class="list1 fright">
                            <li><a href="#">Pellentesque sed dolor  adipiscing elit</a></li>
                            <li><a href="#">Aliquam congue fermentum nisl</a></li>
                            <li><a href="#">Mauris accumsan nulla vel diam sed</a></li>
                        </ul>
                         <ul class="list1 fleft">
                            <li><a href="#">Mauris accumsan nulla vel diam</a></li>
                            <li><a href="#">Sed in lacus ut enim adipiscing aliquet</a></li>
                            <li><a href="#">In pede mi, aliquet sit amet, euismod </a></li>
                        </ul>
                    </div>
                    <br class="clear" />
                </div> 
                
          </div>
      </div>
      <!-- /.content-box -->
    </section>
</div>