


 <h1>hello this is me </h1>


&nbsp;&nbsp;<h2>Search Trucks</h2>

<div class="bdline1">



<div class="bdline1right">

<div class="bdline1rightheader">
Mileage Meter
</div>

<div class="bdline1rightcontent">
<div>
    <form action="#" onSubmit="showLocation(); return false;">
		<p><input class="text" type="text" name="address1" placeholder="Leaving From"/></p>
			<p><input class="text" type="text" name="address2" placeholder="Going To" /></p>
			<p><input class="submit" type="submit" value="Search" /></p>

	</form>
    
    
  <!--  <div id="autoSuggestionsList">
    </div> -->

 





    <div>
 
    <p id="results"></p>
    </div>
	</div>

</div>


</div>


</div>

