
<!-- aside -->
<aside> 
    <div class="indent-block1">
        <div id="carousel">
            <ul id="myRoundabout">
              <li><img src="images/img1.jpg" alt="" /><div class="info"><span class="txt-4">Loads of Business</span></div></li>
              <li><img src="images/img3.jpg" alt="" /><div class="info"><span class="txt-4">Sort your Type of Trailer</span></div></li>
             
              <li><img src="images/img2.jpg" alt="" /><div class="info"><span class="txt-4">Sort your Type of Load</span></div></li>
            </ul>
          </div>
    </div> 
</aside>      
<div id="main">
    <a href="#" class="btnPrev"><img src="images/roundAboutPrev.png" alt=""></a> <a href="#" class="btnNext"><img src="images/roundAboutNext.png" alt=""></a>
    <!-- content -->
    <section id="content">
       <!-- <div class="indent1">
        	<a href="#"><img alt="" src="images/banner1.jpg" class="banner" /></a><a href="#"><img alt="" src="images/banner2.jpg" /></a><br>
        </div>            -->
      <!-- .content-box -->
      <div class="inside1">
      
      
       
                
                
                
                
                
          <div class="content-box">
            <div class="container_12 wrapper">
                <div class="grid_4 alpha">
                	<div class="indent">
                        <h2>Truckers</h2>
                       
                       <div class="view view-first">
                     <img src="../images/truckers.jpg"  alt="Trucks for Loaders" title="Trucks for Loaders" />
                    <!--<img src="../images/pointer.png" class="sprite thumboneone" alt="Loads for Truckers" title="Loads for Truckers" />-->
                    
                  <div class="mask">
                    <h2>Truckers</h2>
                    	 <br />
                         <ul>
                      	 <li>Post Trucks Unlimited</li>
                         <li>Search Freights Unlimited</li>
                         <li>Reliable Broker Credit Scores</li>
                         <li>Search Mulitple Results</li>
                         <li>Get Notification Instantly</li>
                         <br />
                      
                         </ul>
                         
                        
                    </div>
                </div> 
                         
                        <a class="button" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'about',
    									'action' => 'index'));
										?>">Read More </a> 
                                        
                        <div class="indent2">
                        	<h2>Latest Loads</h2>
                            
                            
                            <div class="bdline1left3">
<div class="bdline1leftheader3">
Members can view details about loads
</div>


<div class="bdline1lefttitle3"> 
<div class="2bdline1lefttab1">
</div>
<div class="bdline1lefttab3"><h5>Pickup Time</h5>
</div>
<div class="bdline1lefttab3"><h5>Starting from</h5>
</div>
<div class="bdline1lefttab3"><h5>Destination</h5s>
</div>

</div>


<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
    
    <?php foreach($this->l_data as $load): ?>
      
<div class="bdline1lefttab3"><?php echo $load['pickupDate']?>
</div>
<div class="bdline1lefttab3"><?php echo $load['startCity']?>
</div>
<div class="bdline1lefttab3"><?php echo $load['endCity']?>
</div>
<?php endforeach; ?>
</dt>
	</dl>
  
</div>




	<!-- 
  <div id="2accordion">
  <dl class="2accordion" id="slider">
		<dt>
        
     
<div class="bdline1lefttab3"><?php //echo $load['pickupDate']?>
</div>
<div class="bdline1lefttab3"><?php// echo $load[5]['startCity']?>
</div>
<div class="bdline1lefttab3"><?php //echo $load[5]['endCity']?>
</div>


</dt>

	</dl>

</div>

<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
        
<div class="bdline1lefttab3"><?php //echo $load[4]['pickupDate']?>
</div>
<div class="bdline1lefttab3"><?php// echo $load[4]['startCity']?>
</div>
<div class="bdline1lefttab3"><?php //echo $load[4]['endCity']?>
</div>

</dt>

	</dl>

</div>




<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
        
<div class="bdline1lefttab3"><?php //echo $load[3]['pickupDate']?>
</div>
<div class="bdline1lefttab3"><?php// echo $load[3]['startCity']?>
</div>
<div class="bdline1lefttab3"><?php //echo $load[3]['endCity']?>
</div>

</dt>

	</dl>

</div>



<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
        
<div class="bdline1lefttab3"><?php// echo $load[2]['pickupDate']?>
</div>
<div class="bdline1lefttab3"><?php// echo $load[2]['startCity']?>
</div>
<div class="bdline1lefttab3"><?php// echo $load[2]['endCity']?>
</div>

</dt>

	</dl>

</div>

<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
        
<div class="bdline1lefttab3"><?php //echo $load[1]['pickupDate']?>
</div>
<div class="bdline1lefttab3"><?php //echo $load[1]['startCity']?>
</div>
<div class="bdline1lefttab3"><?php //echo $load[1]['endCity']?>
</div>

</dt>

	</dl>

</div>

<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
        
<div class="bdline1lefttab3"><?php// echo $load[0]['pickupDate']?>
</div>
<div class="bdline1lefttab3"><?php// echo $load[0]['startCity']?>
</div>
<div class="bdline1lefttab3"><?php// echo $load[0]['endCity']?>

</dt>
<?php //endforeach; ?>
	</dl>

</div>


 -->
 </div>

                            
                            
                            <a class="button" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'user',
    									'action' => 'register'));
										?>">Sign up Now</a>
                        </div>
                        
                       <div class="indent2">
                        	<h2>Trucking Resources</h2>
                            
                        <a href="#" class="button3">Trucking Associations</a>
                        <a href="#" class="button3">Freight Factoring</a>
                        <a href="#" class="button3">Important Phone Numbers</a>

                            
                            <a class="button" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'resources',
    									'action' => 'index'));
										?>">View all</a>
                        </div> 
                        
                        
                    </div>
                </div>
                <div class="grid_4">
               		<div class="indent">
                        <h2>Freight Farwarders</h2>
                         <div class="view view-first">
                         
                   <img src="../images/loaders.jpg" alt="Loads for Truckers" title="Loads for Truckers" />      
                   
                   
                    <div class="mask">
                       
                        <h2>Loaders</h2>
                        <br />
                        <ul>
                        <li>Post Unlimited Freight</li>

						<li>Search Unlimited Trucks</li>

						<li>Truck Notification Instantly</li>

						<li>Lane Posting Unlimited </li>
                        
                        <br />
                        
                        
                        
                        </ul>
						
                    </div>
                </div> 
                        <a class="button" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'about',
    									'action' => 'index'));
										?>">Read More </a>
                                
                        <div class="indent2">
                        	<h2>Latest Trucks</h2>
                            
                            
                            <div class="bdline1left3">
<div class="bdline1leftheader3">
Members can view details about Trucks
</div>


<div class="bdline1lefttitle3"> 
<div class="2bdline1lefttab1">
</div>
<div class="bdline1lefttab3"><h5>Pickup Time</h5>
</div>
<div class="bdline1lefttab3"><h5>Starting from</h5>
</div>
<div class="bdline1lefttab3"><h5>Destination</h5>
</div>

</div>


<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
      <?php foreach($this->t_data as $truck):?>  
<div class="bdline1lefttab3"><?php echo $truck['startingDate']; ?>
</div>
<div class="bdline1lefttab3"><?php echo $truck['s_city']; ?>
</div>
<div class="bdline1lefttab3"><?php echo $truck['e_city']; ?>
</div>
<?php endforeach; ?>
</dt>

	</dl>

</div>

<!-- <div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
        
<div class="bdline1lefttab3">11-11-2011
</div>
<div class="bdline1lefttab3">San Jose
</div>
<div class="bdline1lefttab3">San Francisco
</div>

</dt>

	</dl>

</div>

<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
        
<div class="bdline1lefttab3">11-11-2011
</div>
<div class="bdline1lefttab3">San Jose
</div>
<div class="bdline1lefttab3">San Francisco
</div>

</dt>

	</dl>

</div>


<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
        
<div class="bdline1lefttab3">11-11-2011
</div>
<div class="bdline1lefttab3">San Jose
</div>
<div class="bdline1lefttab3">San Francisco
</div>

</dt>

	</dl>

</div>


<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
        
<div class="bdline1lefttab3">11-11-2011
</div>
<div class="bdline1lefttab3">San Jose
</div>
<div class="bdline1lefttab3">San Francisco
</div>

</dt>

	</dl>

</div>


<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
        
<div class="bdline1lefttab3">11-11-2011
</div>
<div class="bdline1lefttab3">San Jose
</div>
<div class="bdline1lefttab3">San Francisco
</div>

</dt>

	</dl>

</div>


<div id="2accordion">


	<dl class="2accordion" id="slider">
		<dt>
        
        
<div class="bdline1lefttab3">11-11-2011
</div>
<div class="bdline1lefttab3">San Jose
</div>
<div class="bdline1lefttab3">San Francisco
</div>

</dt>

	</dl>

</div>

 -->
 </div>
                            
                            
                            <a class="button" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'user',
    									'action' => 'register'));
										?>">Sign up Now</a>
                      </div>
                    <div class="indent2">
                        	<h2>Support</h2>

                        
                        <a href="#" class="button3">Write To Us</a>
                        <a href="#" class="button3">Live Chat</a>
                        <a href="#" class="button3">Live call </a>
                        
                            
                            <a href="more.html" class="button">Apply now!</a>
                        </div> 
                    </div>
                    
                </div>









                <div class="grid_4 omega">
                	<!-- <h2>Hiring area</h2>
                   <a href="#"><img alt="" src="images/banner3.jpg" /></a> -->
                    
                   
                    
                    <div class="indent2">
                   <script type="text/javascript"><!--
google_ad_client = "ca-pub-4906488699730089";
/* v2netsolutions */
google_ad_slot = "5427210395";
google_ad_width = 300;
google_ad_height = 300;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
                    </div>
                    
                    <div class="indent2">
                    	<h2>What 'allstateloads' Does?</h2>
                        <a href="#" class="button3">How It Works</a>
                        <a href="#" class="button3">Frequently Asked Questions</a>
                        <a href="#" class="button3">Testimonials</a>
                    </div>
                    
                    <div class="indent2">
                    	<h2>Share this page</h2>
                       <!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>

<a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ebdd9c64cee229c"></script>

<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>

<!-- AddThis Button END -->
                    </div>
                    
                    
             		<div class="indent2">
                    	<h2>Follow Us on</h2>

<!-- AddThis Button BEGIN -->

<div class="addthis_toolbox addthis_32x32_style addthis_default_style">
<a class="addthis_button_facebook_follow" addthis:userid="33050197131"></a>
<a class="addthis_button_twitter_follow" addthis:userid="winwinhost"></a>

</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ebdd9c64cee229c"></script>
<!-- AddThis Button END -->

<br />
<!-- webim button --><a href="http://localhost/webim/client.php?locale=en&amp;style=default" target="_blank" onclick="if(navigator.userAgent.toLowerCase().indexOf('opera') != -1 &amp;&amp; window.event.preventDefault) window.event.preventDefault();this.newWindow = window.open('http://localhost/webim/client.php?locale=en&amp;style=default&amp;url='+escape(document.location.href)+'&amp;referrer='+escape(document.referrer), 'webim', 'toolbar=0,scrollbars=0,location=0,status=1,menubar=0,width=640,height=480,resizable=1');this.newWindow.focus();this.newWindow.opener=window;return false;"><img src="http://localhost/webim/b.php?i=mblue&amp;lang=en" border="0" width="198" height="49" alt=""/></a><!-- / webim button -->


                    </div>
                    
        
                    
                    </div>
                    
                  
      
    
               
            
            
            
            






                    
                    
                   
                
                </div>
            </div>
          </div>
      </div>
      <!-- /.content-box -->
    </section>
</div>
    

