<!-- <?php			
				
$role = Zend_Auth::getInstance()->getIdentity()->member_role;
			
?> -->

<!-- 
<div id="truck">
    <div id="go"> <p>Go From 
       
         To
         </p>
    </div>
    <div id="data">
        
    </div>
</div>
 --><head>

	<?php echo $this->headScript()->appendFile('/js/script.js') ?>
    <?php echo $this->headScript()->appendFile('/js/packed.js') ?>
    <?php echo $this->headScript()->appendFile('/js/scriptscroller.js') ?>
    
</head>

<div class="mnline1">

<div class="mnline1left">

<div class="mnline1leftheader">
Trucks Posted by You
</div>


<div class="mnline1lefttitle"> 
<div class="mnline1lefttab1">
</div>
<div class="mnline1lefttab">Owner
</div>
<div class="mnline1lefttab">Starting Point
</div>
<div class="mnline1lefttab">Destination
</div>
<div class="mnline1lefttab">Trailer Type
</div>
<div class="mnline1lefttab">Space Status
</div>
<div class="mnline1lefttab">Edit
</div>
<div class="mnline1lefttab">Delete
</div>

</div>

<div id="accordionmn">
 <?php foreach($this->trucks as $truck): ?>
	<dl class="accordionmn" id="slider">
    
		<dt>
       
        <div class="mnline1lefttab1">+
</div>

<div class="mnline1lefttab"><?php echo Zend_Auth::getInstance()->getIdentity()->member_username; ?>
</div>

<div class="mnline1lefttab"> <?php echo $truck['s_city'] . ' '
        . $truck['s_state'] . ' ' . $truck['s_zip'];?> 
</div>

<div class="mnline1lefttab"><?php echo $truck['e_city'] . ' '
        . $truck['e_state'] . ' ' . $truck['e_zip'];?>
</div>

<div class="mnline1lefttab"><?php echo  $truck['type'];?>
</div>
<div class="mnline1lefttab"><?php echo  $truck['full'];?>
</div>
<div class="mnline1lefttab">-----
</div>
<div class="mnline1lefttab">-----
</div>

        
        </dt>
		<dd>
		<span>
		
		<?php printf("Public: %s\nTeam: %s\nWeight: %d\nFeet: %d\nTruckAvaible:
                      %s\nTruck Type: %d\nPhone: %s\n Email: %s, Owner: %s",
                      $truck['public'], $truck['team'], $truck['weight'],
                      $truck['feet'], $truck['full'], $truck['type'],
                      $truck['phone'], $truck['email'], $truck['owner']
         ); ?>
            
      	</span>
		</dd>
        
  <?php endforeach; ?>
	</dl>

</div>

</div>

</div>

<script type="text/javascript">

var slider1=new accordion.slider("slider1");
slider1.init("slider");

</script>


<script type="text/javascript"> 

TINY.scroller.init('scroll','scrollcontent','scrollbar','scroller','buttonclick');
</script>