

<div class="mnline1">

<div class="mnline1left">

<div class="mnline1leftheader">
Trucks Posted by You
</div>


<div class="mnline1lefttitle"> 
<div class="mnline1lefttab0">
</div>
<div class="mnline1lefttab">Owner
</div>
<div class="mnline1lefttab">Starting Point
</div>
<div class="mnline1lefttab">Destination
</div>
<div class="mnline1lefttab">Trailer Type
</div>
<div class="mnline1lefttab">Space Status
</div>
<div class="mnline1lefttab">Edit
</div>
<div class="mnline1lefttab">Delete
</div>
</div>

<div id="accordionmn">
 <?php foreach($this->trucks as $truck): ?>
	<dl class="accordionmn" id="slider">
    
		<dt>
       
        <div class="mnline1lefttab1">
</div>

<div class="mnline1lefttab"><?php echo Zend_Auth::getInstance()->getIdentity()->member_username; ?>
</div>

<div class="mnline1lefttab"> <?php echo $truck['s_city'] . ' '
        . $truck['s_state'] . ' ' . $truck['s_zip'];?> 
</div>

<div class="mnline1lefttab"><?php echo $truck['e_city'] . ' '
        . $truck['e_state'] . ' ' . $truck['e_zip'];?>
</div>

<div class="mnline1lefttab"><?php echo  $truck['type'];?>
</div>
<div class="mnline1lefttab"><?php echo  $truck['full'];?>
</div>
<div class="mnline1lefttab"><img src="/images/edit.png" />
</div>
<div class="mnline1lefttab"><img src="/images/cross.png" />
</div>

        
        </dt>
		<dd>

		<span>
		

    
           Is it Public ? : <?php echo  $truck['public']."<br/>";?><br/>
           Team Driven ?: <?php echo  $truck['team']."<br/>";?><br/>
           Weight Capacity : <?php echo  $truck['weight']."<br/>";?><br/>
           Space  : <?php echo  $truck['feet']."<br/>";?><br/>
           Is it Full : <?php echo  $truck['full']."<br/>";?><br/>
           Type if Truck : <?php echo  $truck['type']."<br/>";?><br/>
           Phone Number : <?php echo  $truck['phone']."<br/>";?><br/>
           Email Address : <?php echo  $truck['email']."<br/>";?><br/>
           Owner  : <?php echo  $truck['owner']."<br/>";?><br/>
            
            
      	</span>
		</dd>
        <?php endforeach; ?>
  
	</dl>

</div>

</div>

</div>

<script type="text/javascript">

var slider1=new accordion.slider("slider1");
slider1.init("slider");

</script>


<script type="text/javascript"> 

TINY.scroller.init('scroll','scrollcontent','scrollbar','scroller','buttonclick');
</script>