<head>  
 
 
    <?php echo $this->headScript()->appendFile('/js/jquery-1.3.2.min.js') ?>
    <?php echo $this->headScript()->appendFile('/js/script.js') ?>
    
    <?php echo $this->headScript()->appendFile('/js/roundabout.js') ?>
    <?php echo $this->headScript()->appendFile('/js/easing.js') ?>
    <?php echo $this->headScript()->appendFile('/js/roundabout_shapes.js') ?>
    
    


</head>  

<div class="line">&nbsp;</div> 

<div id="main">
    <!-- content -->
    <section id="content">               
      <!-- .content-box -->
      <div class="inside1">
          <div class="content-box">
            <div class="container_12 wrapper">
                <div class="grid_8 alpha">
                	<div class="indent">
                        <h2>How allStateLoads Work for Truckers</h2><br />
                       	<div class="wrapper p1"><a href="images/howtruckerswork.jpg"  class="lightbox-image fleft" rel="prettyphoto" title="How allstateloads work for truckers"><img alt="How allstateloads work for truckers" src="images/howtruckerswork0.jpg" class="img-indent3" /></a><a href="images/howtruckersworks.jpg"  class="lightbox-image fleft"  rel="prettyphoto" title="How allstateloads work for truckers"><img alt="How allstateloads work for truckers" src="images/howtruckerswork00.jpg" class="img-indent3" /></a></div>
                        <p><b>Truckers find loads for your truck. Use this system to post your trucks and find the loads that you can carry</b></p>
	                    
                        <p><strong> Truckers do you want to earn extra on your trips , do you want to be your own boss and yet would like to earn same amount of earning as being with a regular company. By using all allstateloads , it is like a freight farwarding companies working for you and not only one but more than one.So each time you check your dashboard you will making choice of picking loads easily and without any hustle.</strong></p>     
                         
                        <p><strong>allstateloads</strong> provides the truckers with best load board options whether its about avilable loads matched with your options , road conditions , weather conditions or posting trucks. Truckers Can Post unlimited trucks with their account ID. Matched loads are viewable immediatedly to you and you can than start doing business with freight farworders.</p>    
                        
                        <p>Trucking companies or individuals can <a href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'user',
    									'action' => 'register'));
										?>">sign up FREE</a> to post empty trucks and get calls from directly from brokers. With our new automatic load-match feature, find available loads for each truck you post.</p>
                        
                                           
                    </div>
                    <div class="indent2">
                    	 <div class="container_8 wrapper">
                         	<div class="grid_4 alpha">
                            	<div class="inside-right1">
                                    <h2>Main Features</h2>
                                    <p><stong>
                                    allstateloads</strong> gives you full controll over your trucks to match freight loads for them as suited. Some of the main features you can use are :</p>
                                    <ul class="list1">                                        
                        <li>Post Trucks Unlimited</li>

						<li>Search Freights Unlimited</li>

						<li> Broker Credit Scores</li>
						<li>Search Mulitple Results</li>

						<li>Get Notification Instantly </li>
                                    </ul>
                                </div>
                            </div>
                         	<div class="grid_4 omega">
                            	<h2> Advantages </h2>
                                <ol>
                                	
                                    <li><h5> Immediate Results</h5> 
                                    	<p>Get Instant <strong>Results </strong>in your <strong>dashboard</strong> or Search Loads views about freight loads that are matched according to your specified time and within your route </p>
                                    </li>
                                    <li><h5> Email Notifications </h5> 
                                    	<p>Get Instant  Email <strong>Notications</strong> when freight loads are matched to your specified time and within your route </p>
                                    </li>
                                </ol>
                            </div>
                         </div>
                    </div>
                </div>
                
                <div class="grid_4 omega">
                	<!-- <h2>Hiring area</h2>
                   <a href="#"><img alt="" src="images/banner3.jpg" /></a> -->
                    
                   
                    
                    <div class="indent2">
                   <script type="text/javascript"><!--
google_ad_client = "ca-pub-4906488699730089";
/* v2netsolutions */
google_ad_slot = "5427210395";
google_ad_width = 300;
google_ad_height = 300;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
                    </div>
                    
                    <div class="indent2">
                    	<h2>What allstateloads Do</h2>
                        <a href="#" class="button3">How It Work</a>
                        <a href="#" class="button3">Frequently Asked Questions</a>
                        <a href="#" class="button3">Testimonials</a>
                    </div>
                    
                    <div class="indent2">
                    	<h2>Share this page</h2>
                       <!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>

<a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ebdd9c64cee229c"></script>

<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>

<!-- AddThis Button END -->
                    </div>
                    
                    
             		<div class="indent2">
                    	<h2>Follow Us on</h2>

<!-- AddThis Button BEGIN -->

<div class="addthis_toolbox addthis_32x32_style addthis_default_style">
<a class="addthis_button_facebook_follow" addthis:userid="33050197131"></a>
<a class="addthis_button_twitter_follow" addthis:userid="winwinhost"></a>

</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ebdd9c64cee229c"></script>
<!-- AddThis Button END -->

<br />
<!-- webim button --><a href="http://localhost/webim/client.php?locale=en&amp;style=default" target="_blank" onclick="if(navigator.userAgent.toLowerCase().indexOf('opera') != -1 &amp;&amp; window.event.preventDefault) window.event.preventDefault();this.newWindow = window.open('http://localhost/webim/client.php?locale=en&amp;style=default&amp;url='+escape(document.location.href)+'&amp;referrer='+escape(document.referrer), 'webim', 'toolbar=0,scrollbars=0,location=0,status=1,menubar=0,width=640,height=480,resizable=1');this.newWindow.focus();this.newWindow.opener=window;return false;"><img src="http://localhost/webim/b.php?i=mblue&amp;lang=en" border="0" width="198" height="49" alt=""/></a><!-- / webim button -->


                    </div>
                    
        
                    
                    </div>
                
                
                <div class="grid_8 alpha">
                	<div class="indent">
                        <h2>How allStateLoads Work for Loaders</h2>
                       	<div class="wrapper p1"><a href="images/howloaderswork.jpg"  class="lightbox-image fleft" rel="prettyphoto" title="How allstateloads work for loaders"><img alt="How allstateloads work for loaders" src="images/howloaderswork0.jpg" class="img-indent3" /></a><a href="images/howloadersworks.jpg"  class="lightbox-image fleft"  rel="prettyphoto" title="How allstateloads work for loaders"><img alt="How allstateloads work for loaders" src="images/howloaderswork00.jpg" class="img-indent3" /></a></div>
                        <p><b>Freight farwarder find trunks. Use this system to post your <em>freight</em> and find the trucks that are suitable for your freight type and distination.</b><p>
                        At allstateloads you can find trucks and drivers of your choice and at your wished time and date.Make a search by yourself or select from the suggested trucks by the system and have a deal before you laod your freight on their trucks
                        </p>
                                              
                    </div>
                    <div class="indent2">
                    	 <div class="container_8 wrapper">
                         	<div class="grid_4 alpha">
                            	<div class="inside-right1">
                                    <h2>Main Features</h2>
                                    <br />
                                  <ul class="list1"> 
                                      <li>Post Unlimited Freight</li>
                                      <li>Search Unlimited Trucks</li>
                                      <li>Truck Notification Instantly</li>
                                      <li>Lane Posting Unlimited</li>
                                  </ul>

                           	  </div>
                            </div>
                         	<div class="grid_4 omega">
                            	<h2> Advantages </h2>
                                <ol>
                                	
                                    <li><h5> Immediate Results</h5> 
                                    	<p>Get Instant <strong>Results </strong>in your <strong>dashboard</strong> or Search Trucks views about trucks that are matched according to your specified time and destinated at same point you require</p>
                                    </li>
                                    <li><h5> Email Notifications </h5> 
                                    	<p>Get Instant  Email <strong>Notications</strong> when trucks are avilable up your specified requirements  </p>
                                    </li>
                                </ol>
                            </div>
                         </div>
                    </div>
                </div>
                
                
            </div>
          </div>
      </div>
      <!-- /.content-box -->
    </section>
</div>




			
			