<div class="line">&nbsp;</div> 

<div id="main">
    <!-- content -->
    <section id="content">               
      <!-- .content-box -->
      <div class="inside1">
          <div class="content-box">
            <div class="container_12 wrapper">
                <div class="grid_8 alpha">
                	<div class="indent">
                        <h2>Latest Updates From <b>allstateloads</b></h2>
                       	<br />
                      
                         
                         
                        <p>
                        <div id="page">
				<?php foreach($this->data as $data): ?>
				<!-- blog post -->
				<div class="blog-post">
					<p class="blog-date"><?php echo $data->news_posted; ?> </p>
					<div class="blog-body">
						<h3><a href="#"><?php echo $data->news_title; ?></a></h3>
						<p>
                        <?php echo $data->news_text; ?>
                        </p>
					</div>
					<div class="clear"></div>
				</div>
				<!-- /blog post -->
				
				
				<?php endforeach; ?>
			</div>
                        </p>                        
                    </div>
                    
                </div>
                
                <div class="grid_4 omega">
                	<h2>Latest news</h2>
                    <ul class="news">
                        <li>
                          <p class="date">08<span>April</span></p>
                          <a href="#" class="title">Parturient montes, nascetur ridiculus mu nulla dui fusce feugiat malesuada odio morbi nunc gravida.</a>
                        </li>
                      </ul>
                      <p>Fusce feugiat malesuada odio. Morbi nunc odio, gravi<br>da at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci... <a href="more.html" class="link">&gt;</a></p>
                   	 <ul class="news">
                        <li>
                          <p class="date">22<span>April</span></p>
                          <a href="#" class="title">Nulla dui fusce feugiat malesuada odio morbi nunc gravida  at, cursus nec, luctus a, lorem naecenas.</a>
                        </li>
                      </ul>
                      <p>Duis ultricies pharetra magna. Done accumsan male-<br>suada orci adipiscing elit.Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapi-<br>bus eget, elementum vel... <a href="more.html" class="link">&gt;</a></p>
                      
                    <a href="more.html" class="button">Viev All News</a>                    
                    <div class="indent2">
                        <h2>Testimonials</h2>
                        <b>Patrick Pool</b>, student, May 18, 2010
                        <p>"Cum sociis natoque penatibus et magnis dis parturi-<br>ent montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem..." <a href="more.html" class="link">&gt;</a></p>
                        <b>Sandra Bullock</b>, driver, May 21, 2010
                        <p>"Morbi nunc odio, gravida at, cursu nec, luctus a lorem maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum..." <a href="more.html" class="link">&gt;</a></p>
                        <b>Alan Smith</b>, driver, June 27, 2010
                        <p>"Nascetur ridiculus mus. Nulla dui. Fusce feugi at mal<br>esuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna..." <a href="more.html" class="link">&gt;</a></p>
                    	<a href="more.html" class="button">More Testimonials</a>           
                    </div>         
                </div>
                
                
                
                
                
            </div>
          </div>
      </div>
      <!-- /.content-box -->
    </section>
</div>

            
            
            
            
      
			
	
            
            
            
            
            
			