<!-- <?php			
						
	$role = Zend_Auth::getInstance()->getIdentity()->member_role;
					
				?> --><head>

	 <?php echo $this->headScript()->appendFile('/js/scriptaccord.js') ?>
   	 <?php echo $this->headScript()->appendFile('/js/packed.js') ?>
    <?php echo $this->headScript()->appendFile('/js/scriptscroller.js') ?>
    
</head>




      


<div id="main">  
      
      <section id="content">

<h2>Manage Your Trucks</h2>


<?php echo $this->partial('partials/truck_all.phtml', array('trucks' => $this->data)); ?>


		





</section>

</div>


