<h1>List Off News Posted</h1>
<table>
    <tr>
        <td>ID</td>
        <td>Title</td>
        <td>Posted</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
<?php foreach($this->data as $news): ?>
    <tr>
        <td><?php echo $news->news_id; ?></td>
        <td><?php echo $news->news_title; ?></td>
        <td><?php echo $news->news_posted; ?></td>
        <td><a href="<?php echo $this->url(array(
            'module' => 'admin', 
            'controller' => 'news',
            'action' => 'edit',
            'id' => $news->news_id)); ?>">Edit</a></td>
        <td><a href="<?php echo $this->url(array(
            'module' => 'admin',
            'controller' => 'news',
            'action' => 'delete',
            'id' => $news->news_id)); ?>/">Delete</a></td>
    </tr>
<?php endforeach; ?>
</table>