<!-- <?php			
	$role = Zend_Auth::getInstance()->getIdentity()->member_role;
     ?> -->

<header>

	<div id="main1">

            
            <div class="member">
    <?php if(!Zend_Auth::getInstance()->hasIdentity()): ?>
            <form action="/user/login" method="post">
          		<input placeholder="Username" class="memberlabel" type="text" name="username" />
               <input class="memberlabel" placeholder="Password"  type="password" name="password" />
                <input class="submit" type="submit" value="Login"/>
                
                <div class="forgot">
               <br /> &nbsp;&nbsp; <a href="<?php echo $this->url(array('module'=>'default', 'controller'=>'user', 'action' => 'recover')) ?>">Forget Password?</a>
                &nbsp;&nbsp; <a href="<?php echo $this->url(array('module'=>'default', 'controller'=>'user', 'action' => 'register')) ?>">Not Member Yet? </a>
               </div>
               
               </form>
            
    <?php else: ?>
    	Loged In as <b><?php echo Zend_Auth::getInstance()->getIdentity()->member_username; ?>
        				
        				
                        
                        </b> 
                        
                       <a href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'user',
    									'action' => 'logout'));?>">  <input class="submit" type="submit" value="Logout"/></a>
                             
    <?php endif; ?>
</div>
    
        
    	<div class="logo"><a href="#">allstateloads</a></div>  
        
        
        
        <?php  if ($role == 2 ): ?> 
         <nav>
            <ul class="sf-menu">
            <li>
              	<?php echo $this->navigation()->menu(); ?> 
                </li>            
            </ul>
          </nav>  
          
        
        
        <?php elseif ($role == 3 ): ?> 
          <nav>
            <ul class="sf-menu">
              	<li>
                <a href="<?php echo $this->url(array(
    									'module' => 'dashboard',
    									'controller' => 'index',
    									'action' => 'index'));
										?>">Dashboard</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'dashboard',
    									'controller' => 'search',
    									'action' => 'loaders'));
										?>">Search Trucks</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'dashboard',
    									'controller' => 'load',
    									'action' => 'add'));
										?>">Post a Load</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'dashboard',
    									'controller' => 'manage',
    									'action' => 'loads'));
										?>">Manage</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'user',
    									'action' => 'profile'));
										?>">Account settings</a>
			</li>                    
            </ul>
          </nav>  
          
          
          
          
          <?php elseif ($role == 4 ):  ?>
          <nav>
            <ul class="sf-menu">
              	<li>
                <a href="<?php echo $this->url(array(
    									'module' => 'dashboard',
    									'controller' => 'index',
    									'action' => 'index'));
										?>">Dashboard</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'dashboard',
    									'controller' => 'search',
    									'action' => 'truckers'));
										?>">Search Loads</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'dashboard',
    									'controller' => 'truck',
    									'action' => 'create'));
										?>">Post a Truck</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'dashboard',
    									'controller' => 'manage',
    									'action' => 'index'));
										?>">Manage</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'user',
    									'action' => 'profile'));
										?>">Account settings</a>
			</li>                    
            </ul>
          </nav>
          
          
          
          <?php else:  ?> 
          <nav>
            <ul class="sf-menu">
              	<li>
                <a href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'index',
    									'action' => 'index'));
										?>">Home</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'about',
    									'action' => 'index'));
										?>">How it works</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'blog',
    									'action' => 'index'));
										?>">Latest News</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'resources',
    									'action' => 'index'));
										?>">Resources</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'user',
    									'action' => 'register'));
										?>">Sign up Now</a>
			</li>
            
            
            <li>
                <a href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'contact',
    									'action' => 'index'));
										?>">Contact Us</a>
			</li>                    
            </ul>
          </nav>
          <?php endif; ?>
	</div>    
</header>

			       
     