<div class="grid_4 omega">
                	<h2>Hiring area</h2>
                   <a href="#"><img alt="" src="images/banner3.jpg" /></a>
                    <div class="indent2">
                    	<h2>Additional services</h2>
                        <a href="more.html" class="button3">Wood packing</a>
                        <a href="more.html" class="button3">Planning your move</a>
                        <a href="more.html" class="button3">Appoint a survey</a>
                    </div>
                   
                    
                    <div class="indent2">
                   <script type="text/javascript"><!--
google_ad_client = "ca-pub-4906488699730089";
/* v2netsolutions */
google_ad_slot = "5427210395";
google_ad_width = 300;
google_ad_height = 300;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
                    </div>
                    
                    
                    <div class="indent2">
                    	<h2>Share this page</h2>
                       <!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>

<a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ebdd9c64cee229c"></script>

<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
<!-- AddThis Button END -->
                    </div>
                    
                    
             		<div class="indent2">
                    	<h2>Follow Us on</h2>

<!-- AddThis Button BEGIN -->
<p>Follow Us</p>
<div class="addthis_toolbox addthis_32x32_style addthis_default_style">
<a class="addthis_button_facebook_follow" addthis:userid="33050197131"></a>
<a class="addthis_button_twitter_follow" addthis:userid="winwinhost"></a>

</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ebdd9c64cee229c"></script>
<!-- AddThis Button END -->


                    </div>
                    
        
                    
                    </div>