<!--		<?php			
			$role = Zend_Auth::getInstance()->getIdentity()->member_role;
			?> -->
<head>

	<?php echo $this->headScript()->appendFile('/js/script.js') ?>
    <?php echo $this->headScript()->appendFile('/js/packed.js') ?>
    <?php echo $this->headScript()->appendFile('/js/scriptscroller.js') ?>
    

   
 
<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAAi0R3quTw1dDEVXhGcF91nxTxAhpynYZ10555ctneyaNYboTkExS_9w2nt91kx5AuybmglX-XA0lPLA" type="text/javascript">  
</script>






<script src=" https://ajax.googleapis.com/ajax/libs/jquery/1.6.3/jquery.min.js" type="text/javascript"></script>
<script>
var geocoder, location1, location2, gDir;
 
function initialize() {
	geocoder = new GClientGeocoder();
	gDir = new GDirections();
	GEvent.addListener(gDir, "load", function() {
		var drivingDistanceMiles = gDir.getDistance().meters / 1609.344;
		var drivingDistanceKilometers = gDir.getDistance().meters / 1000;
		document.getElementById('results').innerHTML = '<strong> <br /><strong><b>Driving Distance:</b> </strong>' + drivingDistanceMiles + ' miles (or ' + drivingDistanceKilometers + ' kilometers)';
                
	});
}
 
function showLocation() {
	geocoder.getLocations(document.forms[0].address1.value, function (response) {
		if (!response || response.Status.code != 200)
		{
			alert("Sorry, we were unable to geocode the first address");
		}
		else
		{
			location1 = {lat: response.Placemark[0].Point.coordinates[1], lon: response.Placemark[0].Point.coordinates[0], address: response.Placemark[0].address};
			geocoder.getLocations(document.forms[0].address2.value, function (response) {
				if (!response || response.Status.code != 200)
				{
					alert("Sorry, we were unable to geocode the second address");
				}
				else
				{
					location2 = {lat: response.Placemark[0].Point.coordinates[1], lon: response.Placemark[0].Point.coordinates[0], address: response.Placemark[0].address};
					gDir.load('from: ' + location1.address + ' to: ' + location2.address);
				}
			});
		}
	});
}
</script>


</head>


<body onLoad="initialize()" >

        
                &nbsp;&nbsp;<h2>Dashboard</h2>
                                
                

<?php  if ($role == 2 ): ?>



<div class="bdline1">


<div id="scroll">
		<div id="scrollcontent">



<div class="bdline1left">
<div class="bdline1leftheader">
Suggested Loads 
</div>


<div class="bdline1lefttitle"> 
<div class="bdline1lefttab1">
</div>
<div class="bdline1lefttab">Load ID 
</div>
<div class="bdline1lefttab">Pickup Date
</div>
<div class="bdline1lefttab">Delivery Date
</div>
<div class="bdline1lefttab">Starting Point
</div>
<div class="bdline1lefttab">Destination
</div>


</div>



<div id="accordion">
<?php foreach($this->states as $dd): ?>
    
     <?php if($dd['owner'] != Zend_Auth::getInstance()->getIdentity()->member_id): ?>
	<dl class="accordion" id="slider">
		<dt>
        
        <div class="bdline1lefttab1">+
</div>
<div class="bdline1lefttab"><?php echo $dd['id']."<br />"; ?>
</div>
<div class="bdline1lefttab"><?php echo $dd['pickupDate']."<br />"; ?>
</div>
<div class="bdline1lefttab"><?php echo $dd['diliveryDate']."<br />"; ?>
</div>
<div class="bdline1lefttab"><?php echo $dd['startCity']."<br />"; ?>
</div>
<div class="bdline1lefttab"><?php echo $dd['endCity']."<br />"; ?>
</div>

        
        </dt>
		<dd>
		<span>
        
       <div class="loadsdesc">

       <img class="loadsdes" src="images/templogo.png" alt="Truckers" />
       

       
       <span>
        Company : <?php echo $dd['extra']."<br />"; ?>  <br>
		Phone Number  : <?php echo $dd['phone']."<br />"; ?>  <br>
        Email Address : <?php echo $dd['email']."<br /><br />"; ?>  <br>
        
        Space Required: <?php echo $dd['feet']."Square feet"."<br />"; ?>  <br>
        Weight of the Load  : <?php echo $dd['weight']."Kilograms"."<br />"; ?>  <br>
       
       </span>
       
       </div> 
        


</span>
		</dd>
      <?php endif; ?>      
        <?php endforeach; ?>

	</dl>
        
    
</div>



</div>

            
  
            
            
		</div>
		<div id="scrollbar">
			<div id="scroller" class="scroller"></div>
		</div>
	</div>





 <?php elseif ($role == 3 ): ?>  




<div class="bdline1">


<div id="scroll">
		<div id="scrollcontent">



<div class="bdline1left">
<div class="bdline1leftheader">
Suggested Trucks
</div>


<div class="bdline1lefttitle"> 
<div class="bdline1lefttab1">
</div>
<div class="bdline1lefttab">Pickup Date
</div>
<div class="bdline1lefttab">Starting Point
</div>
<div class="bdline1lefttab">Destination
</div>
<div class="bdline1lefttab"> Trailer Type
</div>
<div class="bdline1lefttab">Company
</div>
</div>






</div>

            
  
            
            
		</div>
		<div id="scrollbar">
			<div id="scroller" class="scroller"></div>
		</div>
	</div>


</div>



<?php elseif ($role == 4 ):  ?>  





<div class="bdline1">


<div id="scroll">
		<div id="scrollcontent">



<div class="bdline1left">
<div class="bdline1leftheader">
Suggested Loads 
</div>


<div class="bdline1lefttitle"> 
<div class="bdline1lefttab1">
</div>
<div class="bdline1lefttab">Load ID 
</div>
<div class="bdline1lefttab">Pickup Date
</div>
<div class="bdline1lefttab">Delivery Date
</div>
<div class="bdline1lefttab">Starting Point
</div>
<div class="bdline1lefttab">Destination
</div>

</div>



<div id="accordion">
<?php foreach($this->states as $dd): ?>
	<dl class="accordion" id="slider">
		<dt>
        
        <div class="bdline1lefttab1">+
</div>
<div class="bdline1lefttab"><?php echo $dd['id']."<br />"; ?>
</div>
<div class="bdline1lefttab"><?php echo $dd['pickupDate']."<br />"; ?>
</div>
<div class="bdline1lefttab"><?php echo $dd['diliveryDate']."<br />"; ?>
</div>
<div class="bdline1lefttab"><?php echo $dd['startCity']."<br />"; ?>
</div>
<div class="bdline1lefttab"><?php echo $dd['endCity']."<br />"; ?>
</div>

        
        </dt>
		<dd>
		<span>
Company : <?php echo $dd['extra']."<br />"; ?>  <br>
Phone Number  : <?php echo $dd['phone']."<br />"; ?>    <br>

</span>
		</dd>
        
        <?php endforeach; ?>

	</dl>
        
    
</div>



</div>

            
  
            
            
		</div>
		<div id="scrollbar">
			<div id="scroller" class="scroller"></div>
		</div>
	</div>


</div>






<?php endif; ?>




<div class="bdline1right">

<div class="bdline1rightheader">
Mileage Meter
</div>

<div class="bdline1rightcontent">
<div>


    <form action="#" onSubmit="showLocation(); return false;">
		<p><input class="text" type="text" name="address1" placeholder="Leaving From"/></p>
			<p><input class="text" type="text" name="address2" placeholder="Going To" /></p>
			<p><input class="submit" type="submit" value="Get Mileage" /></p>

	</form>
    
    
  <!--  <div id="autoSuggestionsList">
    </div> -->







    <div >
 
    <p id="results"></p>
    </div>
	</div>

</div>


</div>
</div>



<!-- <div id="truck-side">
    <h3>Truck Actions</h3>
    <ul>
        <li><a href="/dashboard/truck">All Trucks</a></li>
        <li><a href="/dashboard/index/my-trucks">My Truck List</a></li>
        <li><a href="/dashboard/truck/create">Add Truck</a></li>
    </ul>
</div>

<br />
<br />
<br /><br /><br />
<br /><br />
<br /><br /><br /><br /><br />
<br />
<br />
<br />




<div id="load-side">
    <h3>Load Actions</h3>
    <ul>
        <li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'load', 'action' => 'index')); ?>">All Loads</a></li>
        <li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'load', 'action' => 'mytrucks')); ?>">My Loads List</a></li>
        <li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'load', 'action' => 'add')); ?>">Add Load</a></li>

    </ul>
</div>

-->

<br />
<br /><br /><br />
<br /><br />
<br /><br /><br /><br /><br />
<br />
<br />




    <script type="text/javascript">

var slider1=new accordion.slider("slider1");
slider1.init("slider");

</script>


<script type="text/javascript"> 

TINY.scroller.init('scroll','scrollcontent','scrollbar','scroller','buttonclick');
</script>


