<head>
    
<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAAi0R3quTw1dDEVXhGcF91nxQ1sRGNLtyg8HYxXnoIHRD9vHc6-BREVpm5dKZ3_QruLVZLwlOuiAQDiQ" type="text/javascript">  
</script>
<script src=" https://ajax.googleapis.com/ajax/libs/jquery/1.6.3/jquery.min.js" type="text/javascript"></script>
<script>
var geocoder, location1, location2, gDir;
 
function initialize() {
	geocoder = new GClientGeocoder();
	gDir = new GDirections();
	GEvent.addListener(gDir, "load", function() {
		var drivingDistanceMiles = gDir.getDistance().meters / 1609.344;
		var drivingDistanceKilometers = gDir.getDistance().meters / 1000;
		document.getElementById('results').innerHTML = '<strong> <br /><strong><b>Driving Distance:</b> </strong>' + drivingDistanceMiles + ' miles (or ' + drivingDistanceKilometers + ' kilometers)';
                
	});
}
 
function showLocation() {
	geocoder.getLocations(document.forms[0].address1.value, function (response) {
		if (!response || response.Status.code != 200)
		{
			alert("Sorry, we were unable to geocode the first address");
		}
		else
		{
			location1 = {lat: response.Placemark[0].Point.coordinates[1], lon: response.Placemark[0].Point.coordinates[0], address: response.Placemark[0].address};
			geocoder.getLocations(document.forms[0].address2.value, function (response) {
				if (!response || response.Status.code != 200)
				{
					alert("Sorry, we were unable to geocode the second address");
				}
				else
				{
					location2 = {lat: response.Placemark[0].Point.coordinates[1], lon: response.Placemark[0].Point.coordinates[0], address: response.Placemark[0].address};
					gDir.load('from: ' + location1.address + ' to: ' + location2.address);
				}
			});
		}
	});
}
</script>


</head>





&nbsp;&nbsp;<h2>Manage </h2>

<div class="bdline1">

<div class="bdline1left">
<div class="bdline1leftheader">
Suggested Loads
</div>


<div class="bdline1lefttitle"> 
<div class="bdline1lefttab1">
</div>
<div class="bdline1lefttab">Pickup Date
</div>
<div class="bdline1lefttab">Starting Point
</div>
<div class="bdline1lefttab">Destination
</div>
<div class="bdline1lefttab">Trailer Type
</div>
<div class="bdline1lefttab">Company
</div>
</div>



<div id="accordion">
	<dl class="accordion" id="slider">
		<dt>
        
        <div class="bdline1lefttab1">+
</div>
<div class="bdline1lefttab">----
</div>
<div class="bdline1lefttab">----
</div>
<div class="bdline1lefttab">----
</div>
<div class="bdline1lefttab">----
</div>
<div class="bdline1lefttab">----
</div>
        
        </dt>
		<dd>
		<span>---- <br />----<br />----<br />-------- <br />----<br />----<br />-------- <br />----<br />----<br />----</span>
		</dd>
        
 
        
        
	</dl>
</div>









</div>

<div class="bdline1right">

<div class="bdline1rightheader">
Mileage Meter
</div>

<div class="bdline1rightcontent">
<div>
    <form action="#" onSubmit="showLocation(); return false;">
		<p><input class="text" type="text" name="address1" placeholder="Leaving From"/></p>
			<p><input class="text" type="text" name="address2" placeholder="Going To" /></p>
			<p><input class="submit" type="submit" value="Search" /></p>

	</form>
    
    
  <!--  <div id="autoSuggestionsList">
    </div> -->







    <div>
 
    <p id="results"></p>
    </div>
	</div>

</div>


</div>




<div id="truck-side">
    <h3>Truck Actions</h3>
    <ul>
        <li><a href="/dashboard/truck">All Trucks</a></li>
        <li><a href="/dashboard/index/my-trucks">My Truck List</a></li>
        <li><a href="/dashboard/truck/create">Add Truck</a></li>
    </ul>
</div>

<br />
<br />
<br /><br /><br />
<br /><br />
<br /><br /><br /><br /><br />
<br />
<br />
<br />




<div id="load-side">
    <h3>Load Actions</h3>
    <ul>
        <li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'load', 'action' => 'index')); ?>">All Loads</a></li>
        <li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'load', 'action' => 'mytrucks')); ?>">My Loads List</a></li>
        <li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'load', 'action' => 'add')); ?>">Add Load</a></li>

    </ul>
</div>



<br />
<br /><br /><br />
<br /><br />
<br /><br /><br /><br /><br />
<br />
<br />